### ISSUE TITLE
装载mod后游戏无法启动

### ISSUE THREAD

**Issue by Alfrecid** [LucunJi/BedrockBreakHelper#5]
使用的是0.6.7-1375版MultiMc,   fabric-api-0.3.0+build.200,
malilib-fabric-1.14.4-0.10.0-dev.20,   Bedrock.Break.Helper-1.5-1.14.4

在装载mod之后无法启动游戏，控制台日志如下：
[15:16:53] [main/INFO]: Loading for game Minecraft 1.14.4
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: Failed to resolve mods!
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:147)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:120)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	... 8 more
Caused by: net.fabricmc.loader.discovery.ModResolutionException: Could not resolve valid mod collection (at: bbhelper requires {fabricloader @ [>=0.7.2]})
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:185)
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:504)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:145)
	... 10 more
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81)
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401)
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:183)
	... 12 more
Exiting with -1
进程退出，代码：-1。

**Comment by LucunJi** [comment]
`Could not resolve valid mod collection (at: bbhelper requires {fabricloader @ [>=0.7.2]})`
Fabric loader 版本不够，至少安装0.7.2即以上的fabric加载器。
如果还是不能解决请reopen
